/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiagnosisRouteImport } from './routes/api/diagnosis'
import { Route as ApiScenariosRouteImport } from './routes/api/scenarios'
import { Route as ApiTelemetryScenarioIdRouteImport } from './routes/api/telemetry.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosisRoute = ApiDiagnosisRouteImport.update({
  id: '/api/diagnosis',
  path: '/api/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenariosRoute = ApiScenariosRouteImport.update({
  id: '/api/scenarios',
  path: '/api/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryScenarioIdRoute = ApiTelemetryScenarioIdRouteImport.update({
  id: '/api/telemetry/$scenarioId',
  path: '/api/telemetry/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/diagnosis': typeof ApiDiagnosisRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/telemetry/$scenarioId': typeof ApiTelemetryScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/diagnosis': typeof ApiDiagnosisRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/telemetry/$scenarioId': typeof ApiTelemetryScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/diagnosis': typeof ApiDiagnosisRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/telemetry/$scenarioId': typeof ApiTelemetryScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/diagnosis' | '/api/scenarios' | '/api/telemetry/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/diagnosis' | '/api/scenarios' | '/api/telemetry/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/api/diagnosis'
    | '/api/scenarios'
    | '/api/telemetry/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDiagnosisRoute: typeof ApiDiagnosisRoute
  ApiScenariosRoute: typeof ApiScenariosRoute
  ApiTelemetryScenarioIdRoute: typeof ApiTelemetryScenarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnosis': {
      id: '/api/diagnosis'
      path: '/api/diagnosis'
      fullPath: '/api/diagnosis'
      preLoaderRoute: typeof ApiDiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenarios': {
      id: '/api/scenarios'
      path: '/api/scenarios'
      fullPath: '/api/scenarios'
      preLoaderRoute: typeof ApiScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/$scenarioId': {
      id: '/api/telemetry/$scenarioId'
      path: '/api/telemetry/$scenarioId'
      fullPath: '/api/telemetry/$scenarioId'
      preLoaderRoute: typeof ApiTelemetryScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDiagnosisRoute: ApiDiagnosisRoute,
  ApiScenariosRoute: ApiScenariosRoute,
  ApiTelemetryScenarioIdRoute: ApiTelemetryScenarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
