import type { VehicleRepository } from '@/application/ports/VehicleRepository.js'
import type { LoggerPort } from '@/application/ports/LoggerPort.js'
import { PidDefinition } from '@/domain/entities/pidDefinition.js'
import type { DtcDefinition } from '@/domain/entities/dtcDefinition.js'
import {
  SYSTEM_BATTERY,
  SYSTEM_EMISSIONS,
  SYSTEM_ENGINE,
  SYSTEM_EXHAUST,
  SYSTEM_TRANSMISSION,
  SYSTEM_VEHICLE,
} from '@/domain/systemVocabulary.js'
import { PidCode } from '@/domain/value-objects/pidCode.js'

/** Confianza asignada a los DTCs manufacturer-specific del seed (fuente documentada VAG/Ross-Tech). */
const SEED_DTC_CONFIDENCE = 0.9

/**
 * PIDs Mode 22 (UDS ReadDataByIdentifier) propietarios de fabricante, seed de BD.
 * Datos movidos desde el antiguo `seed-pids.ts` para que el codigo solo conserve
 * lo universal (SAE J1979/J2012).
 *
 * Se construyen con {@link PidDefinition} (no literales) para que corra la
 * validacion del constructor: `name.trim`, `dataBytes >= 1`, `confidence ∈ [0,1]`.
 */
const MANUFACTURER_PID_SEEDS: PidDefinition[] = [
  // ── Toyota Auris Hybrid ──
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '0300'),
    name: 'TCU Odometer',
    system: SYSTEM_TRANSMISSION,
    formula: '(A<<24|B<<16|C<<8|D)/10',
    unit: 'km',
    dataBytes: 4,
    pidType: 'formula',
    confidence: 0.9,
    source: 'seed',
    description: 'Kilometraje almacenado en la Transmission Control Unit',
    minValue: 0,
    maxValue: 999999,
    manufacturer: 'Toyota',
    model: 'Auris Hybrid',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '0400'),
    name: 'ECM Odometer',
    system: SYSTEM_ENGINE,
    formula: '(A<<24|B<<16|C<<8|D)/10',
    unit: 'km',
    dataBytes: 4,
    pidType: 'formula',
    confidence: 0.9,
    source: 'seed',
    description: 'Kilometraje almacenado en la Engine Control Module',
    minValue: 0,
    maxValue: 999999,
    manufacturer: 'Toyota',
    model: 'Auris Hybrid',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '7A76'),
    name: 'Hybrid Battery State of Charge',
    system: SYSTEM_BATTERY,
    formula: 'A*0.5',
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 0.85,
    source: 'seed',
    minValue: 0,
    maxValue: 100,
    manufacturer: 'Toyota',
    model: 'Auris Hybrid',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '7A53'),
    name: 'Hybrid Battery Voltage',
    system: SYSTEM_BATTERY,
    formula: '(A*256+B)*0.01',
    unit: 'V',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 0.85,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Toyota',
    model: 'Auris Hybrid',
  }),

  // ── Audi A3 (VAG 2.0 TDI, Ross-Tech DIDs) ──
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1130'),
    name: 'Engine Speed',
    system: SYSTEM_ENGINE,
    formula: '(A*256+B)/4',
    unit: 'rpm',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 16383.75,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '115C'),
    name: 'Charge Air Pressure Actual',
    system: SYSTEM_ENGINE,
    formula: 'A*256+B',
    unit: 'mbar',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 65535,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '115E'),
    name: 'Charge Air Pressure Specified',
    system: SYSTEM_ENGINE,
    formula: 'A*256+B',
    unit: 'mbar',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 65535,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F430'),
    name: 'Coolant Temperature',
    system: SYSTEM_ENGINE,
    formula: 'A',
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 255,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F432'),
    name: 'Intake Air Temperature',
    system: SYSTEM_ENGINE,
    formula: 'A',
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 255,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F477'),
    name: 'Fuel Rail Pressure Actual',
    system: SYSTEM_ENGINE,
    formula: '(A*256+B)*0.01',
    unit: 'bar',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F47D'),
    name: 'Fuel Rail Pressure Specified',
    system: SYSTEM_ENGINE,
    formula: '(A*256+B)*0.01',
    unit: 'bar',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1035'),
    name: 'EGR Duty Cycle',
    system: SYSTEM_EMISSIONS,
    formula: 'A',
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 255,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1250'),
    name: 'Engine Torque',
    system: SYSTEM_ENGINE,
    formula: 'A*256+B',
    unit: 'Nm',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 65535,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1132'),
    name: 'Injection Quantity',
    system: SYSTEM_ENGINE,
    formula: '(A*256+B)*0.01',
    unit: 'mg/stroke',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1184'),
    name: 'Intake Air Mass',
    system: SYSTEM_ENGINE,
    formula: 'A*256+B',
    unit: 'mg/stroke',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 65535,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1410'),
    name: 'DPF Soot Mass',
    system: SYSTEM_EXHAUST,
    formula: '(A*256+B)*0.01',
    unit: 'g',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '140E'),
    name: 'DPF Differential Pressure',
    system: SYSTEM_EXHAUST,
    formula: 'A*256+B',
    unit: 'mbar',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 65535,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F449'),
    name: 'Accelerator Pedal Position',
    system: SYSTEM_VEHICLE,
    formula: 'A',
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 255,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', '1462'),
    name: 'Battery Voltage',
    system: SYSTEM_BATTERY,
    formula: '(A*256+B)/100',
    unit: 'V',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 655.35,
    manufacturer: 'Audi',
    model: 'A3',
  }),
  new PidDefinition({
    id: 0,
    pidCode: new PidCode('22', 'F40D'),
    name: 'Vehicle Speed',
    system: SYSTEM_VEHICLE,
    formula: 'A',
    unit: 'km/h',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'seed',
    minValue: 0,
    maxValue: 255,
    manufacturer: 'Audi',
    model: 'A3',
  }),
]

/** DTCs manufacturer-specific (VAG/diesel) movidos desde el antiguo `dtcCatalog.ts`. */
const MANUFACTURER_DTC_SEEDS: Array<Omit<DtcDefinition, 'id' | 'createdAt'>> = [
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1004',
    description: 'Intake Manifold Runner Control Valve Malfunction',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1011',
    description: 'Fuel Rail Pressure Too Low',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1128',
    description: 'Fuel Trim System Too Lean (Bank 1, Multiplicative)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1136',
    description: 'Long Term Fuel Trim Additive Fuel System Too Lean (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1403',
    description: 'Exhaust Gas Recirculation Valve Position Sensor Circuit Malfunction',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P1602',
    description: 'Engine Control Module Supply Voltage Too Low',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2002',
    description: 'Diesel Particulate Filter Efficiency Below Threshold (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2004',
    description: 'Intake Manifold Runner Control Stuck Open (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2006',
    description: 'Intake Manifold Runner Control Stuck Closed (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2008',
    description: 'Intake Manifold Runner Control Circuit/Open (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2015',
    description: 'Intake Manifold Runner Position Sensor/Switch Circuit Range/Performance (Bank 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2031',
    description: 'Exhaust Gas Temperature Sensor Circuit (Bank 1, Sensor 2)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2080',
    description: 'Exhaust Gas Temperature Sensor Circuit Range/Performance (Bank 1, Sensor 1)',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2100',
    description: 'Throttle Actuator Control Motor Circuit/Open',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2101',
    description: 'Throttle Actuator Control Motor Circuit Range/Performance',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2111',
    description: 'Throttle Actuator Control System — Stuck Open',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P244B',
    description: 'Diesel Particulate Filter Differential Pressure Too High',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2454',
    description: 'Diesel Particulate Filter Pressure Sensor "A" Circuit Low',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2459',
    description: 'Diesel Particulate Filter Regeneration Frequency',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2463',
    description: 'Diesel Particulate Filter — Soot Accumulation',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P246C',
    description: 'Diesel Particulate Filter Restriction — Forced Engine Shutdown',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2564',
    description: 'Turbocharger Boost Control Position Sensor Circuit Low',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
  {
    manufacturer: 'Audi',
    model: 'A3',
    code: 'P2610',
    description: 'ECM/PCM Internal Engine Off Timer Performance',
    confidence: SEED_DTC_CONFIDENCE,
    source: 'seed',
  },
]

/**
 * Seed idempotente del catálogo de fabricante en BD.
 *
 * Inserta los PIDs Mode 22 (propietarios) y los DTCs manufacturer-specific que
 * antes vivían hardcodeados en `seed-pids.ts` y `dtcCatalog.ts`. No duplica:
 * para PIDs comprueba con {@link VehicleRepository.findPidDefinition} antes de
 * insertar (porque `insertPidDefinition` no deduplica); para DTCs delega en
 * {@link VehicleRepository.upsertDtcDefinition}, que ya deduplica por clave
 * única (manufacturer + model + code).
 *
 * @param vehicleRepo - Puerto de persistencia del catálogo auto-expansivo.
 * @param logger - Logger para trazar el resultado del seed.
 */
export async function seedManufacturerCatalog(
  vehicleRepo: VehicleRepository,
  logger: LoggerPort,
): Promise<void> {
  let pidsInserted = 0
  for (const pid of MANUFACTURER_PID_SEEDS) {
    const existing = await vehicleRepo.findPidDefinition(
      pid.pidCode.mode,
      pid.pidCode.pid,
      pid.manufacturer,
      pid.model,
    )
    if (existing) continue
    await vehicleRepo.insertPidDefinition(pid)
    pidsInserted += 1
  }

  for (const dtc of MANUFACTURER_DTC_SEEDS) {
    await vehicleRepo.upsertDtcDefinition(dtc)
  }

  logger.info('Manufacturer catalog seeded', {
    pidsInserted,
    dtcsSeeded: MANUFACTURER_DTC_SEEDS.length,
  })
}
