packages:
  - 'apps/*'

allowBuilds:
  '@scarf/scarf': false
  bcrypt: set this to true or false
  better-sqlite3: set this to true or false
  esbuild: true
  onnxruntime-node: true
  png-img: false
  protobufjs: true
  sharp: true
  wd: false

onlyBuiltDependencies:
  - '@scarf/scarf'
  - bcrypt
  - better-sqlite3
  - esbuild

overrides:
  protobufjs: '>=7.5.5'
  handlebars: '>=4.7.7'
  uglify-js: '>=3.18.0'
  form-data: '>=2.5.4'
