import type { PidDefinition } from '@/domain/entities/pidDefinition.js'
import { SYSTEM_ENGINE, SYSTEM_VEHICLE } from '@/domain/systemVocabulary.js'
import { Formula } from '@/domain/value-objects/formula.js'
import { PidCode } from '@/domain/value-objects/pidCode.js'

/** PIDs estándar Mode 01 (SAE J1979) — globales, para cualquier vehículo. */
export const STANDARD_MODE_01_PIDS: PidDefinition[] = [
  {
    id: 0,
    pidCode: new PidCode('01', '04'),
    name: 'Calculated Engine Load',
    system: SYSTEM_ENGINE,
    formula: new Formula('A*100/255'),
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    description: 'Engine load calculated by the ECU',
  },
  {
    id: 0,
    pidCode: new PidCode('01', '05'),
    name: 'Engine Coolant Temperature',
    system: SYSTEM_ENGINE,
    formula: new Formula('A-40'),
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -40,
    maxValue: 215,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '06'),
    name: 'Short Term Fuel Trim — Bank 1',
    system: SYSTEM_ENGINE,
    formula: new Formula('A*100/128-100'),
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -100,
    maxValue: 99.2,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '07'),
    name: 'Long Term Fuel Trim — Bank 1',
    system: SYSTEM_ENGINE,
    formula: new Formula('A*100/128-100'),
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -100,
    maxValue: 99.2,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '0B'),
    name: 'Intake Manifold Absolute Pressure',
    system: SYSTEM_ENGINE,
    formula: new Formula('A'),
    unit: 'kPa',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 255,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '0C'),
    name: 'Engine RPM',
    system: SYSTEM_ENGINE,
    formula: new Formula('(A*256+B)/4'),
    unit: 'rpm',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 16383.75,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '0D'),
    name: 'Vehicle Speed',
    system: SYSTEM_VEHICLE,
    formula: new Formula('A'),
    unit: 'km/h',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 255,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '0E'),
    name: 'Timing Advance',
    system: SYSTEM_ENGINE,
    formula: new Formula('A/2-64'),
    unit: '° before TDC',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -64,
    maxValue: 63.5,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '0F'),
    name: 'Intake Air Temperature',
    system: SYSTEM_ENGINE,
    formula: new Formula('A-40'),
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -40,
    maxValue: 215,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '10'),
    name: 'Mass Air Flow Rate',
    system: SYSTEM_ENGINE,
    formula: new Formula('(A*256+B)/100'),
    unit: 'g/s',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 655.35,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '11'),
    name: 'Throttle Position',
    system: SYSTEM_ENGINE,
    formula: new Formula('A*100/255'),
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 100,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '2F'),
    name: 'Fuel Tank Level Input',
    system: SYSTEM_VEHICLE,
    formula: new Formula('A*100/255'),
    unit: '%',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 100,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '31'),
    name: 'Distance Traveled Since Codes Cleared',
    system: SYSTEM_ENGINE,
    formula: new Formula('A*256+B'),
    unit: 'km',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 65535,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '42'),
    name: 'Control Module Voltage',
    system: SYSTEM_ENGINE,
    formula: new Formula('(A*256+B)/1000'),
    unit: 'V',
    dataBytes: 2,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: 0,
    maxValue: 65.535,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '46'),
    name: 'Ambient Air Temperature',
    system: SYSTEM_VEHICLE,
    formula: new Formula('A-40'),
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -40,
    maxValue: 215,
  },
  {
    id: 0,
    pidCode: new PidCode('01', '5C'),
    name: 'Engine Oil Temperature',
    system: SYSTEM_ENGINE,
    formula: new Formula('A-40'),
    unit: '°C',
    dataBytes: 1,
    pidType: 'formula',
    confidence: 1.0,
    source: 'manual',
    minValue: -40,
    maxValue: 210,
  },
]

/** Todos los PIDs de catálogo disponibles como seed data.
 * Solo PIDs universales SAE J1979 (Mode 01), aplicables a cualquier vehículo.
 * El VIN (Service 09 PID 02) se lee por {@link readVin} con `parseVinResponse`,
 * no por el catálogo de fórmulas, por lo que no necesita definición de seed.
 * Los PIDs Mode 22 (propietarios de fabricante) se cargan desde la BD en runtime
 * vía {@link seedManufacturerCatalog}, no desde código.
 */
export const ALL_SEED_PIDS: PidDefinition[] = [...STANDARD_MODE_01_PIDS]
